export const GET_PROJECT = "GET_PROJECT";
export const GET_PROJECTS_LOAD = "GET_PROJECTS_LOAD";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";
export const TOGGLE_TRUE = "TOGGLE_TRUE";
export const TOGGLE_FALSE = "TOGGLE_FALSE"