export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_LOAD = "GET_PROFILE_LOAD";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";
export const TOGGLE_TRUE = "TOGGLE_TRUE";
export const TOGGLE_FALSE = "TOGGLE_FALSE"